---
title: "Practicals 3"
subtitle: "Mean, Covariance and Corelation of Bivariate data"
author: "Your Name (Reg.No)"
output: html_notebook
---

Consider the data on the height (in inches) and weight (in lbs.) of 20 college-age males
from the file `HeightWeight.txt`. 

**Questions:**

- Plot the scatter plot Height, Weight and Height Vs Weight
- Find the mean vector, covariance matrix and correlation matrix.
- Using matrix operation, create a new dataset where the hei
ght and weight information from the observations are measured in metres and kilogr
ams, respectively, in the height and weight data of 20 college-age males.

  - Calculate the covariance between height and weight in the new dataset. Compare it to the covariance in the original dataset. Do you see a difference?
  - Calculate as well the correlation between height and weight in the new dataset using the matrix operation on the covariance matrix. Compare it to the correlation in the original dataset. Do you now see a difference?
